name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-bot:
    runs-on: ubuntu-latest
    env:
      ENV: test
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
      BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LLM_COMMENTARY: true
      TELEGRAM_HEALTH_ALERTS: false
      RETRAIN_INTERVAL_MINUTES: 30
      CCXT_FALLBACK_LIMIT: 1000
      MODEL_REFRESH_INTERVAL: 5
      LLM_BACKEND: openai

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Required Env Vars
        run: python .github/scripts/validate_env.py

      - name: Test Telegram + Bybit Pipeline
        run: python tests/test_pipeline.py

      - name: Test Data Collection (Bybit + CCXT Fallback)
        run: python tests/test_data_pipeline.py

      - name: Test LLM Alerts
        run: python tests/test_llm_alert.py

      - name: LLM Log Output (Optional Debug)
        if: always()
        run: cat data/signal_log.txt || true
